debug: false
listen:
    port: 3001
cache:
    type: redis
    timeout: 6000
    redis:
        address: localhost:6379
target:
    url: "http://localhost:4000" # this is the base url addressed by the headless Chrome instance, it can be simply your website url
backend:
    url: "http://localhost:4000" # your backend server url
headless:
    instances:
        - http://localhost:9222
        - http://localhost:9223
        - http://localhost:9224
        - http://localhost:9225
        - http://localhost:9226
    waitAfterDOMLoad: 2000
filters:
    userAgent: # .i.e. only whitelist useragents containing the keywords "bot", "slurp", "bing" or "crawler"
        defaultPolicy: blacklist
        exceptions:
            keywords:
                - bot
                - slurp
                - bing
                - crawler
                - google 
                - baidu
                - bing 
                - msn
                - duckduckbot
                - teoma
                - slurp
                - yandex
server:
  enable: true
