debug: false
listen:
    port: 3001
cache:
    type: redis
    timeout: 6000
    redis:
        address: localhost:6379
target:
    url: "http://localhost:4000" # this is the base url addressed by the headless Chrome instance, it can be simply your website url
backend:
    url: "http://localhost:4000" # your backend server url
headless:
    instances:
        - http://localhost:9223
        - http://localhost:9224
        - http://localhost:9225
        - http://localhost:9226
        - http://localhost:9227
        - http://localhost:9228
        - http://localhost:9229
        - http://localhost:9230
        - http://localhost:9231
        - http://localhost:9232
        - http://localhost:9233
        - http://localhost:9234
        - http://localhost:9235
        - http://localhost:9236
        - http://localhost:9237
        - http://localhost:9238
        - http://localhost:9239
        - http://localhost:9240
        - http://localhost:9241
        - http://localhost:9242
        - http://localhost:9243
    waitAfterDOMLoad: 3000
output:
    minify: true
filters:
    userAgent: # .i.e. only whitelist useragents containing the keywords "bot", "slurp", "bing" or "crawler"
        defaultPolicy: blacklist
        exceptions:
            keywords:
                - google
                - bing
                - duckduckbot
                - yahoo
    paths:
        defaultPolicy: whitelist
        exceptions:
            prefix:
             - /store/
             - /search
             - /editorial/
             - /thank-you
            exact:
             - /thank-you
             - /search
    extensions:
        - .css
        - .js
        - .txt
        - .ico
server:
  enable: true
